#!/usr/bin/env bash
# arg1 path/to/workspace

ws=$1 # workspace

chmod -R 775 $(pwd)

if [ ! -e ~/bash_files ]; then
  ln -s $(pwd)/bash_related/bash_files ~/bash_files
fi

if grep -Fxq "export WORKSPACE=REPLACE_ME" ~/bash_files/.bullhorn_variables
then
  sed -i "s#REPLACE_ME#\"$ws\"#" ~/bash_files/.bullhorn_variables
fi

if [ -f ~/.bashrc ]; then
    mv ~/.bashrc ~/.bashrc.backup
fi

cp $(pwd)/bash_related/.bashrc ~/.bashrc

. ~/.bashrc