#!/usr/bin/env bash
# arg1 path/to/workspace

ws=$1 # workspace

sed -i "1s#^/export WORKSPACE=$ws\n#" .bashrc

chmod -R 775 $(pwd)/..

if [ ! -f ~/bash_files ]; then
    ln -s $(pwd)/bash_files ~/bash_files
fi

if [ -f ~/.bashrc ]; then
    mv ~/.bashrc ~/.bashrc.backup
fi

cp $(pwd)/.bashrc ~/.bashrc
sed -i "1s#^/export WORKSPACE=$ws\n#" ~/.bashrc

source ~/.bashrc

